apiVersion: skaffold/v3
kind: Config
metadata:
  name: sonora
build:
  artifacts:
    - image: harbor.cyverse.org/de/sonora
      docker:
        dockerfile: Dockerfile
      platforms:
        - linux/amd64
manifests:
  rawYaml:
    - k8s/sonora.yml
